import { FaCaretDown } from "react-icons/fa";
import { FaCaretUp } from "react-icons/fa";

const data = [
  {
    id: 1,
    name: "Akash Roy",
    age: 21,
    designation: "Buisness Analyst",
    hours: "7(21)",
    changes: 1.5,
    imageUrl: "images/profile8.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },
  {
    id: 2,
    name: "Sarah Yadav",
    age: 40,
    designation: "Product Manager",
    hours: "7(40)",
    changes: 1.5,
    imageUrl: "images/profile3.jpeg",
    arrow: <FaCaretUp color="green"/>,
  },
  {
    id: 3,
    name: "Ankita Thakur",
    age: 41,
    designation: "HR Recruiter",
    hours: "7(41)",
    changes: 1.5,
    imageUrl: "images/profile2.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },

  {
    id: 4,
    name: "Harsha Shivhare",
    age: 37,
    designation: "Designer",
    hours: "7(37)",
    changes: 1.5,
    imageUrl: "images/profile4.jpeg",
    arrow: <FaCaretUp color="green"/>,
  },
  {
    id: 5,
    name: "Vanhi Rai",
    age: 37,
    designation: "Video Editor",
    hours: "7(37)",
    changes: 1.5,
    imageUrl: "images/profile5.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },
  {
    id: 6,
    name: "Suraj Chauhan",
    age: 18,
    designation: "Developer",
    hours: "7(18)",
    changes: 1.5,
    imageUrl: "images/profile2.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },
  {
    id: 7,
    name: "Sunil Yadav",
    age: 24,
    designation: "Developer",
    hours: "7(24)",
    changes: 1.5,
    imageUrl: "images/profile7.jpeg",
    arrow: <FaCaretUp color="green"/>,
  },
  {
    id: 8,
    name: "Rakesh Sharma",
    age: 42,
    designation: "UI/UX Designer",
    hours: "7(42)",
    changes: 1.5,
    imageUrl: "images/download.jpeg",
    arrow: <FaCaretUp color="green"/>,
  },
  {
    id: 9,
    name: "Bhanu Sharma",
    age: 32,
    designation: "Buisness Analyst",
    hours: "7(32)",
    changes: 1.5,
    imageUrl: "images/profile6.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },
  {
    id: 10,
    name: "Rohit Soni",
    age: 20,
    designation: "Developer",
    hours: "7(20)",
    changes: 1.5,
    imageUrl: "images/profile2.jpeg",
    arrow: <FaCaretDown color="red"/>,
  },
];

export default data;
